version: '3.8'

services:
  postgresql:
    image: postgres:16.3-alpine3.20
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${HOST_PATH}:/hostpath